// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: answer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO answer (
  task_id,
  profile_id,
  result
) VALUES (
  $1, $2, $3
)
`

type InsertAnswerParams struct {
	TaskID    pgtype.UUID
	ProfileID string
	Result    AnswerResult
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAnswer, arg.TaskID, arg.ProfileID, arg.Result)
	return err
}
