// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Profile struct {
	ID        string
	Name      string
	AvatarUrl sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	UpdatedAt time.Time
	CreatedAt time.Time
}
