// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        string
	Name      string
	AvatarUrl pgtype.Text
	FirstName pgtype.Text
	LastName  pgtype.Text
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
