name: 'Deploy dev'


on:
  push:
    branches:
      - master

jobs:
  upload-dev-mage:
    runs-on: ubuntu-latest
    name: Upload docker dev image
    env:
      IMAGE_TAG: ${{ github.run_number }}
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps: 
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.DEV_GCP_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Login to Artifact Registry
        uses: 'docker/login-action@v1'
        with:
          registry: 'europe-central2-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and upload image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64 
          tags: | 
            europe-central2-docker.pkg.dev/just-code-dev/just-code-dev/just-code-dev:${{ env.IMAGE_TAG }}
            europe-central2-docker.pkg.dev/just-code-dev/just-code-dev/just-code-dev:latest
          push: true
